@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json

###
post http://{{host}}/auth/login
Content-Type: {{contentType}}

{
    "email": "mateo.doda@outlook.com",
    "password": "mateododa"
}

###
get http://{{host}}/movies/suggestions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hdGVvLmRvZGFAb3V0bG9vay5jb20iLCJ1c2VySWQiOiI2MjQyN2FhYWM4YTgzMTA5ZTBmZTQ0YmYiLCJpYXQiOjE2NDg1NzY3NzcsImV4cCI6MTY0ODU4MDM3N30.RW2VeW2VqcanfIdA06_jPS063CFZnfrAdUu9AvN9ue8


###
post http://{{host}}/movies/approve-movie/6232d0a61f48263258a321e5

###

delete http://{{host}}/movies/deny-movie/623cbe8b622e693a014e06d0

###
post http://{{host}}/auth/signup
Content-Type: {{contentType}}

{
    "name": "Mateo",
    "email": "mateo.doda@outlook.com",
    "password": "mateododa"
}

###
# ADD MOVIE 
post http://{{host}}/movies/add-movie
Content-Type: {{contentType}}

{
    "title": "Captain America: The Winter Soldier",
    "yearPublished": "2014",
    "rating": "PG-13",
    "minutes": "136 min",
    "genre": "Action",
    "imageUrl": "newdvdreleasedates.com/images/posters/full/captain-america-the-winter-soldier-2014-11.jpg",
    "description": "As Steve Rogers struggles to embrace his role in the modern world, he teams up with a fellow Avenger and S.H.I.E.L.D agent, Black Widow, to battle a new threat from history: an assassin known as the Winter Soldier.",
    "starRating": "5"
}

###
# DELETE MOVIE
delete http://{{host}}/movies/delete-movie/6243a97d95ca263bb0ae47a1

###
# UPDATE MOVIE
put http://{{host}}/movies/update-movie/623cbe8b622e693a014e06d4
Content-Type: {{contentType}}

{
    "title": "What Dreams May Come",
    "yearPublished": "1998",
    "rating": "PG-13",
    "minutes": "113 min",
    "genre": "Drama",
    "imageUrl": "https://s5.mzstatic.com/us/r30/Video/f1/c1/1d/mzi.lyxyuotc.jpg",
    "description": "Chris Nielsen dies in an accident, and enters Heaven. But when he discovers that his beloved wife Annie has killed herself out of grief over the loss, he embarks on an afterlife adventure to reunite with her.",
    "starRating": "5"
}