@hostname = localhost
@port = 8080
@host = {{hostname}}:{{port}}
@contentType = application/json

post http://{{host}}/movies/approve-movie/62336331c6977d973559befc
###

delete http://{{host}}/movies/deny-movie/62336331c6977d973559befc


###
post http://{{host}}/auth/signup
Content-Type: {{contentType}}

{
    "name": "Mateo",
    "email": "mateo.doda@outlook.com",
    "password": "mateododa"
}

###
post http://{{host}}/movies/add-movie
Content-Type: {{contentType}}

{
    "title": "The Amazing Spiderman 2",
    "yearPublished": "2014",
    "rating": "PG-13",
    "minutes": "141 min",
    "genre": "Action",
    "imageUrl": "https://buzz.tt/media/posters/511/posters_0_1500.jpg"
}

###
delete http://{{host}}/movies/delete-movie/623a0874e55f43521e02828c